# https://docs.travis-ci.com/user/languages/go/
sudo: false
language: go
go:
  - 1.x
go_import_path: github.com/earlzo/colly-bolt-storage
cache:
  directories:
    - $GOPATH/github.com/earlzo/colly-bolt-storage/vendor

stages:
  - lint
  - test
  - deploy

jobs:
  include:
    - stage: lint
      script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0
        - golangci-lint run
    - stage: test
      script:
        - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: deploy
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: curl -sL http://git.io/goreleaser | bash
        on:
          tags: true
          branch: master
          condition: $TRAVIS_OS_NAME = linux
notifications:
  webhooks:
    - https://oapi.dingtalk.com/robot/send?access_token=7d48ecc5d7d61de7165e655ab9f44dfb02fb6a35223f80beef151d6e082e4e1f
